local M = {}

function M.get(c)
	return {
		Normal = { fg = c.grey3, bg = c.bg },
		NormalNC = { fg = c.grey3, bg = c.bg },
		NormalFloat = { fg = c.white, bg = c.bg1 },
		FloatBorder = { fg = c.outline, bg = c.bg1 },
		FloatTitle = { fg = c.white, bg = c.bg1, bold = true },
		ColorColumn = { bg = c.bg2 },
		Conceal = { fg = c.grey2 },
		CurSearch = { fg = c.bg, bg = c.yellow },
		Cursor = { fg = c.bg, bg = c.white },
		lCursor = { link = "Cursor" },
		CursorIM = { link = "Cursor" },
		CursorColumn = { bg = c.bg2 },
		CursorLine = { bg = c.bg2 },
		CursorLineNr = { fg = c.white },
		CursorLineFold = { link = "CursorLineNr" },
		CursorLineSign = { link = "CursorLine" },
		Directory = { fg = c.blue },
		DiffAdd = { bg = c.diff_add },
		DiffChange = { bg = c.diff_mod },
		DiffDelete = { bg = c.diff_del },
		DiffText = { bg = c.diff_add_strong },
		EndOfBuffer = { fg = c.bg },
		ErrorMsg = { fg = c.red },
		FoldColumn = { fg = c.grey1 },
		Folded = { fg = c.grey2, bg = c.bg2 },
		IncSearch = { fg = c.bg, bg = c.orange },
		LineNr = { fg = c.grey1 },
		LineNrAbove = { link = "LineNr" },
		LineNrBelow = { link = "LineNr" },
		MatchParen = { fg = c.orange, bold = true },
		ModeMsg = { fg = c.white, bold = true },
		MoreMsg = { fg = c.green },
		MsgArea = { fg = c.grey3 },
		MsgSeparator = { fg = c.outline, bg = c.bg },
		NonText = { fg = c.grey1 },
		Pmenu = { fg = c.white, bg = c.bg1 },
		PmenuSel = { bg = c.blue },
		PmenuKind = { fg = c.grey2, bg = c.bg1 },
		PmenuKindSel = { fg = c.grey2, bg = c.blue },
		PmenuExtra = { fg = c.grey2, bg = c.bg1 },
		PmenuExtraSel = { fg = c.grey2, bg = c.blue },
		PmenuSbar = { bg = c.bg1 },
		PmenuThumb = { bg = c.outline },
		Question = { fg = c.green },
		QuickFixLine = { bg = c.bg3, bold = true },
		Search = { fg = c.bg, bg = c.yellow },
		SignColumn = { fg = c.grey1 },
		SpecialKey = { fg = c.grey1 },
		SpellBad = { undercurl = true, sp = c.red },
		SpellCap = { undercurl = true, sp = c.yellow },
		SpellLocal = { undercurl = true, sp = c.blue },
		SpellRare = { undercurl = true, sp = c.green },
		StatusLine = { fg = c.grey3, bg = c.bg2 },
		StatusLineNC = { fg = c.grey2, bg = c.bg },
		Substitute = { fg = c.bg, bg = c.orange },
		TabLine = { fg = c.grey2, bg = c.bg2 },
		TabLineFill = { bg = c.bg },
		TabLineSel = { fg = c.white, bg = c.bg, bold = true },
		TermCursor = { link = "Cursor" },
		TermCursorNC = { bg = c.grey2 },
		Title = { fg = c.white, bold = true },
		Visual = { bg = c.bg4 },
		VisualNOS = { link = "Visual" },
		WarningMsg = { fg = c.yellow },
		Whitespace = { fg = c.grey1 },
		WildMenu = { link = "PmenuSel" },
		WinBar = { fg = c.grey3, bg = c.bg },
		WinBarNC = { fg = c.grey2, bg = c.bg },
		WinSeparator = { fg = c.outline_dim },
	}
end

return M
