local M = {}

function M.get(c)
	return {
		["@variable"] = { fg = c.white },
		["@variable.builtin"] = { fg = c.orange },
		["@variable.parameter"] = { fg = c.white },
		["@variable.member"] = { fg = c.grey2 },
		["@constant"] = { fg = c.cyan },
		["@constant.builtin"] = { fg = c.orange },
		["@constant.macro"] = { fg = c.orange },
		["@module"] = { fg = c.yellow },
		["@module.builtin"] = { fg = c.orange },
		["@label"] = { fg = c.grey2 },
		["@string"] = { fg = c.teal },
		["@string.documentation"] = { fg = c.grey2 },
		["@string.regexp"] = { fg = c.grey3 },
		["@string.escape"] = { fg = c.orange },
		["@string.special"] = { fg = c.orange },
		["@string.special.symbol"] = { fg = c.cyan },
		["@string.special.url"] = { fg = c.teal, underline = true },
		["@character"] = { fg = c.teal },
		["@character.special"] = { fg = c.orange },
		["@boolean"] = { fg = c.cyan },
		["@number"] = { fg = c.cyan },
		["@number.float"] = { fg = c.orange },
		["@type"] = { fg = c.yellow },
		["@type.builtin"] = { fg = c.yellow },
		["@type.definition"] = { fg = c.yellow },
		["@attribute"] = { fg = c.grey2 },
		["@attribute.builtin"] = { fg = c.grey2 },
		["@property"] = { fg = c.grey2 },
		["@function"] = { fg = c.orange },
		["@function.builtin"] = { fg = c.orange },
		["@function.call"] = { fg = c.orange },
		["@function.macro"] = { fg = c.orange },
		["@function.method"] = { fg = c.orange },
		["@function.method.call"] = { fg = c.orange },
		["@function.macro.rust"] = { fg = c.orange },
		["@constructor"] = { fg = c.yellow },
		["@operator"] = { fg = c.grey2 },
		["@keyword"] = { fg = c.grey2 },
		["@keyword.coroutine"] = { fg = c.grey2 },
		["@keyword.function"] = { fg = c.grey2 },
		["@keyword.operator"] = { fg = c.grey2 },
		["@keyword.import"] = { fg = c.grey2 },
		["@keyword.type"] = { fg = c.grey2 },
		["@keyword.modifier"] = { fg = c.grey2 },
		["@keyword.repeat"] = { fg = c.grey2 },
		["@keyword.return"] = { fg = c.grey2 },
		["@keyword.debug"] = { fg = c.grey2 },
		["@keyword.exception"] = { fg = c.grey2 },
		["@keyword.conditional"] = { fg = c.grey2 },
		["@keyword.conditional.ternary"] = { fg = c.grey2 },
		["@keyword.directive"] = { fg = c.grey2 },
		["@keyword.directive.define"] = { fg = c.grey2 },
		["@punctuation.delimiter"] = { fg = c.grey2 },
		["@punctuation.bracket"] = { fg = c.grey2 },
		["@punctuation.special"] = { fg = c.grey2 },
		["@comment"] = { fg = c.comment, italic = true },
		["@comment.documentation"] = { fg = c.grey2, italic = true },
		["@comment.error"] = { fg = c.red },
		["@comment.warning"] = { fg = c.yellow },
		["@comment.todo"] = { fg = c.cyan, bold = true },
		["@comment.note"] = { fg = c.cyan },

		-- Semantic tokens
		["@lsp.type.class"] = { fg = c.yellow },
		["@lsp.type.decorator"] = { fg = c.grey2 },
		["@lsp.type.enum"] = { fg = c.yellow },
		["@lsp.type.enumMember"] = { fg = c.cyan },
		["@lsp.type.function"] = { fg = c.orange },
		["@lsp.type.interface"] = { fg = c.yellow },
		["@lsp.type.macro"] = { fg = c.orange },
		["@lsp.type.method"] = { fg = c.orange },
		["@lsp.type.namespace"] = { fg = c.white },
		["@lsp.type.parameter"] = { fg = c.white },
		["@lsp.type.property"] = { fg = c.white },
		["@lsp.type.struct"] = { fg = c.yellow },
		["@lsp.type.type"] = { fg = c.yellow },
		["@lsp.type.typeParameter"] = { fg = c.yellow },
		["@lsp.type.variable"] = { fg = c.white },
		["@lsp.mod.deprecated"] = { strikethrough = true },
		["@lsp.mod.readonly"] = { fg = c.white },
		["@lsp.mod.defaultLibrary"] = {},
		["@lsp.typemod.function.defaultLibrary"] = { fg = c.orange },
		["@lsp.typemod.variable.defaultLibrary"] = {},

		-- Rust
		["@lsp.type.property.rust"] = { fg = c.grey2 },
		["@lsp.type.lifetime.rust"] = { fg = c.yellow },
		["@lsp.type.selfKeyword.rust"] = { fg = c.cyan },
		["@lsp.type.selfTypeKeyword.rust"] = { fg = c.cyan },
		["@lsp.typemod.generic.attribute.rust"] = c.variant == "dark" and { fg = c.grey2 } or {},

		-- ts
		["@type.builtin.typescript"] = { fg = c.orange },
		["@variable.member.typescript"] = { fg = c.cyan },

		-- tsx
		["@type.tsx"] = { fg = c.white },
		["@tag.tsx"] = { fg = c.yellow },

		-- json
		["@property.json"] = { fg = c.orange },

		-- Markup
		["@markup.heading"] = { fg = c.cyan, bold = true },
		["@markup.heading.1"] = { fg = c.cyan, bold = true },
		["@markup.heading.2"] = { fg = c.cyan, bold = true },
		["@markup.heading.3"] = { fg = c.cyan, bold = true },
		["@markup.heading.4"] = { fg = c.cyan, bold = true },
		["@markup.heading.5"] = { fg = c.cyan, bold = true },
		["@markup.heading.6"] = { fg = c.cyan, bold = true },
		["@markup.strong"] = { fg = c.white, bold = true },
		["@markup.italic"] = { fg = c.yellow, italic = true },
		["@markup.strikethrough"] = { fg = c.grey2, strikethrough = true },
		["@markup.underline"] = { underline = true },
		["@markup.quote"] = { fg = c.yellow, italic = true },
		["@markup.math"] = { fg = c.cyan },
		["@markup.link"] = { fg = c.orange },
		["@markup.link.label"] = { fg = c.cyan },
		["@markup.link.url"] = { fg = c.orange, underline = true },
		["@markup.raw"] = { fg = c.teal },
		["@markup.raw.block"] = { fg = c.white },
		["@markup.raw.markdown_inline"] = { fg = c.teal },
		["@markup.list"] = { fg = c.orange },
		["@markup.list.checked"] = { fg = c.green },
		["@markup.list.unchecked"] = { fg = c.grey2 },

		-- Tags (JSX/HTML)
		["@tag"] = { fg = c.grey2 },
		["@tag.attribute"] = { fg = c.pink },
		["@tag.delimiter"] = { fg = c.grey2 },
		["@tag.builtin"] = { fg = c.teal },
	}
end

return M
